### ISSUE TITLE
Getting rid of config-editor.js

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5-build-classic#10]
Couldn't we just have an entry named `config` in `config-build.js` with the configurations of the built editor? 

This would allow one to be focused in one file only. Also, a common task will be adding features, having two files to remember to touch just makes it more painful. Or when I remove one plugin, I forget to remove it from the other file.

In few words, it would just make it simpler.

**Comment by Reinmar** [comment]
Hm... hm... That might be possible. And having one file is indeed better.

I'd call the property `editorConfig` for clarity why there's config in the config.

So, we'll be left with on config file so we could change its name back to `build-config.js` which sounds better.

**Comment by Reinmar** [comment]
I've just realised that this may limit heavily what options can be set in the editor config. Currently, `config-editor` could import any editor code so e.g. you can do this:

```js
/**
 * @license Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md.
 */

'use strict';

const SomeExtraPlugin = require( '@ckeditor/ckeditor5-...' ).default;

module.exports = {
        extraPlugins: [ SomeExtraPlugin ],
	toolbar: [
		'headings',
		'bold',
		'italic',
		'link',
		'unlink',
		'bulletedList',
		'numberedList',
		'undo',
		'redo'
	],

	image: {
		toolbar: [ 'imageStyleFull', 'imageStyleSide', '|' , 'imageTextAlternative' ]
	}
};
```

If we move editor config to the build config this won't be possible because such a `require()` call will also be executed by Node.js when we run the task to update the entry file.

So, I'm afraid that keeping the configs separately is safer.

OTOH, if someone wants such a things to work then he/she can edit `ckeditor.js` and import proper stuff directly there. We don't expect to have too many config options (if any) which accept some plugins or other editor classes.

**Comment by fredck** [comment]
I'm afraid that adding or remove whatever to the editor will always involve touching both files (plugin in one file and toolbar in the other). I would prefer to prioritize outsiders and make it simpler for them to handle it. I would go with merging the files and figure out how to handle more complex cases later.

**Comment by Reinmar** [comment]
There will be no "later" – if we go with one file we won't be able to import ES6 and non-Node stuff there.

But I agree that prioritising simplicity is better in this case. There's always the option to directly specify config in `ckeditor.js` if one needs to. There, you can do whatever you want because only a bundler touches this file.

**Comment by Reinmar** [comment]
Just to make it clear what is the easiest way around – if we'll place the config in the `build-config.js`, then `ckeditor.js` can import it like this:

```js
config: require( './build-config.js' ).config;
```

The only problem with this solution (other than what we discussed above) is that it will make the bundle slightly bigger because the entire contents of `build-config.js` will be included.

**Comment by Reinmar** [comment]
After second thought – let's copy the config to `ckeditor.js` to avoid this issue. It will be slightly time-consuming but it's worth to have it right in builds.
