### ISSUE TITLE
Classic editor does not work in firefox

### ISSUE THREAD

**Issue by hultberg** [ckeditor/ckeditor5-build-classic#34]
JSFiddle: https://jsfiddle.net/tv5x6zuj/

Hello. I was integrating the new CKEditor and I noticed that it did not work at all in firefox. I then thought this was something wrong with my installation, but I also noticed the examples in the documentation did not work either. This is reproducible in the linked jsfiddle.

Error message: `TypeError: e.on is not a function`

It works in chromium.

**Comment by Reinmar** [comment]
All works fine for me:

![image](https://user-images.githubusercontent.com/156149/34501882-33722234-f011-11e7-81e4-cc274901543e.png)

Are you sure that you use an up to date version of Firefox?

**Comment by hultberg** [comment]
@Reinmar Thanks. A co-worker also confirmed it was working. I'm using the latest stable (57.0.3 64-bit linux). CKeditor worked after disabling "Vimium" addon (https://github.com/philc/vimium), I'm opening an issue there.

**Comment by Reinmar** [comment]
Good to hear :).

BTW, the error you get made me think that perhaps they are poorly overriding `Element#addEventListener()`. See https://github.com/ckeditor/ckeditor5/issues/683#issuecomment-346582285. Zone.js fixed their code but since we expect to see more issues like this (and some more stubborn or slower-reacting projects) we recently changed our way of checking whether something is a native DOM node or not. We should be safer in the future and, hopefully, the problem you had will not appear in the next version of CKEditor 5.

**Comment by gdh1995** [comment]
Yes, Vimium has hooked `Element::addEventListener` since https://github.com/philc/vimium/pull/2871 .

Why not use `instanceof Element` to do such a check? An demo:
``` javascript
var isNative = (function() {
  var ElementClass = typeof Element === "function" ? Element : HTMLElement;
  return function(el) { return el instanceof ElementClass; };
})();
```

**Comment by Reinmar** [comment]
> Yes, Vimium has hooked Element::addEventListener since philc/vimium#2871 .

It's a bad practice to override native methods. They should be very careful when doing so. CKEditor is not the only project using lodash's `isNative()` which does `toString() ~= [native code]` check.

> Why not use instanceof Element to do such a check? A demo:

It's not that simple because of iframes, but yes – we switched to this approach: https://github.com/ckeditor/ckeditor5-utils/blob/master/src/dom/isdomnode.js

**Comment by gdh1995** [comment]
Well, since zone.js, [Raven.js](https://github.com/getsentry/raven-js) and Vimium have hooked `addEventListener`, I think it's a real and necessary need to do this. But if only someone wants to keep `isNative`, then these libraries and extensions will **have to hook `Function.prototype.toString` too** - if more than one extension does this, the result will be:
``` javascript
let cur = Function.prototype.toString; // what's can be used on console
let i = 0;
for (let prev; prev = cur[Symbol.Scopes][0]["originalFunctionToString"]; cur = prev) {
  // in Chrome console, `[[Scopes]]` shows closures
  i++;
}
console.log(i); // 3, 4, 5 ???
```

So does it for `addEventListener`. This result is so annoying that I suggest all projects stop checking `isNative(*.addEventListener)` for the purpose of checking elements.
