### ISSUE TITLE
Webpack dependencies, Yarn

### ISSUE THREAD

**Issue by VincentClair** [ckeditor/ckeditor5-build-classic#4]
Hello,

I have not installed globally some dependencies:
- style-loader
- raw-loader
- css-loader
- sass-loader
- node-sass

So i get many errors before i can build the package. Maybe those dependencies have to be added to package.json ?

Also, have you studied using yarn to fix dependencies versions and commit yarn.lock file ?

**Comment by Reinmar** [comment]
> So i get many errors before i can build the package. Maybe those dependencies have to be added to package.json ?

Oops. Right. I moved the script for rebuilding the package at the very end of the review and I must have had these dependencies installed somewhere else. Thanks for checking!

> Also, have you studied using yarn to fix dependencies versions and commit yarn.lock file ?

We're watching Yarn constantly and I've been even testing that it works well for CKEditor. We may consider switching to it at some point but we don't want to do it prematurely. If it's gonna stabilise (it didn't work for CKEditor until some point) and get widely adopted (e.g. by Lerna – and I know they are working on it) then it might be an option. But we must be careful to not actually force people to use Yarn because npm is still the standard. For example, we'd have to decide which one to use in our documentation. If we go with npm in the docs, we should also use npm on the daily basis – otherwise we risk that we'll miss some issues. So, it won't be an easy choice.
