### ISSUE TITLE
Problem with webpack in production

### ISSUE THREAD

**Issue by giorgiopagnoni** [ckeditor/ckeditor5-build-classic#44]
I don't know if this is specific to the classic build, but whenever I try to compile this for production with yarn with `yarn encore production`, I get this error:

```
...
admin.js from UglifyJs
Unexpected character '`'
``` 

This is how i use it: `CK = require('@ckeditor/ckeditor5-build-classic');`

It works correctly in development mode.

**Comment by ma2ciek** [comment]
Hi @giorgiopagnoni,

Thanks for reporting the issue.

Could you provide more details?

What does exactly `yarn encore production` do? Does it come from https://github.com/symfony/webpack-encore? Because we don't provide such script and I can't guess what exactly webpack config is generated from that command.

The usage of `UglifyJs` makes me feel, that your ecosystem might doesn't support ES6+ as that minifier doesn't support newer versions of JavaScript. If it's the problem, I encourage you to build the ES5 version of the `@ckeditor/ckeditor5-build-classic` package - [see the docs](https://docs.ckeditor.com/ckeditor5/latest/builds/guides/integration/advanced-setup.html#option-building-to-es5-target).

**Comment by giorgiopagnoni** [comment]
[You pointed me in the right direction](https://github.com/symfony/webpack-encore/issues/139#issuecomment-322592989). Thank you!

**Comment by ma2ciek** [comment]
We have a discussion about providing ES5-compatible builds. You can follow that link: https://github.com/ckeditor/ckeditor5-build-classic/issues/24.
