### ISSUE TITLE
Automate rebuilding the editor before publishing

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-build-classic#6]
I've just noticed that I forgot to rebuild the editor before publishing it ;<

It'd be good to automate this so it never happens again. However, I'm not sure if we can freely add npm prepublish hook for that because that will happen already after tagging the release. So, we either need some earlier hook or to somehow integrate this with our release tools.

**Comment by Reinmar** [comment]
PS. There would be no problem if we haven't kept bundles in the repo, but I'd like them to be here. So, that's why I'd like to commit new bundles before the release is tagged.

**Comment by Comandeer** [comment]
The only gotcha with `prepublish` hook is that it also run in case of `npm install` in npm <= 4. Therefore to detect if `prepublish` is really exec as a part of publish process [`in-publish` package can be used](https://github.com/BEMQuery/bemquery-package-boilerplate/blob/master/package.json#L21).

**Comment by Reinmar** [comment]
OK, I guess I don't know enough about the process. I thought that it goes like this: first, you bump up the version and tag that change. And then you publish that to npm.

**Comment by Reinmar** [comment]
Actually, I can see that you're building your package on `preversion`: https://github.com/BEMQuery/bemquery-package-boilerplate/blob/master/package.json#L19. That makes sense to me. But I'm not entirely sure that our release tool uses `npm version`. If not, perhaps it should.

**Comment by Comandeer** [comment]
I build it on `preversion` just because I'd like to have `dist/` directory on `master` branch when new release is created.

The whole process is rather simple:
* `npm version <type>` bumps the `version` in `package.json` and if it's executed inside git repository, it also create git tag (but it doesn't push anything and that's why I'm doing it manually in `postversion`. That's everything `npm version <type>` does, so if you have custom logic for bumping version (just like e.g. semantic-release), that's totally fine.
* `npm publish` publishes the current state of package to npm. And by "current state" I mean _real_ current state, so what it finds in the CWD when the command is executed (it's even possible to have two totally different versions on GitHub and npm; actually semantic-release does something like this: it publishes version on GitHub without `version` in `package.json` yet publishes to npm with it). That's why I'm rebuilding package on `prepublish` just to be sure that I have the same files in these two places.

**Comment by Reinmar** [comment]
> I build it on preversion just because I'd like to have dist/ directory on master branch when new release is created.

That's exactly what we want too! :D

**Comment by Reinmar** [comment]
This is must-have. I again forgot to rebuilt the builds before publishing everything.
