### ISSUE TITLE
Trying to import local build in React throws error

### ISSUE THREAD

**Issue by Robyrogers** [ckeditor/ckeditor5-build-classic#81]
I am trying to configure an existing build according to the documentation but importin the build to React throws an error in lodash-es depenedency

This the error:
./src/ckeditor5-build-classic/node_modules/lodash-es/_baseClone.js
Line 151: 'keysIn' is not defined no-undef

If I use the build from npm that one is working fine

**Comment by Robyrogers** [comment]
I am trying to configure an existing build according to the documentation but importin the build to React throws an error in lodash-es depenedency

This the error:
./src/ckeditor5-build-classic/node_modules/lodash-es/_baseClone.js
   Line 151:  'keysIn' is not defined  no-undef

If I use the build from npm that one is working fine

**Comment by ma2ciek** [comment]
Hi, @Robyrogers.

Why you import the GH uncompiled resources instead of the NPM build? If you want to customize the build, then you should build the `ckeditor5-build-classic` using the `npm run build` function and then import file from `ckeditor5-build-classic/build/ckeditor`. Or import the resources directly and configure the webpack configuration files.

**Comment by Robyrogers** [comment]
> Hi, @Robyrogers.
> 
> Why you import the GH uncompiled resources instead of the NPM build? If you want to customize the build, then you should build the `ckeditor5-build-classic` using the `npm run build` function and then import file from `ckeditor5-build-classic/build/ckeditor`. Or import the resources directly and configure the webpack configuration files.

![Screenshot from 2019-07-29 10-25-29](https://user-images.githubusercontent.com/11811491/62021849-3b30de00-b1eb-11e9-9130-de7bc3b12bbd.png)

@ma2ciek I am currently importing from `ckeditor5-build-classic/build/ckeditor` that I cloned into the src folder of my React App. I have also run `yarn install` followed by `yarn run build` inside `ckeditor5-build-classic` folder. However, I am still receiving the following errors as seen in the screenshot. Am I doing something wrong somewhere?

**Comment by ma2ciek** [comment]
As I see the problem is with your linter, that tries to lint the build. So you should somehow exclude the `ckeditor5-build-classic` directory from linting. See that actually all of these are linter warnings.

**Comment by Robyrogers** [comment]
I am having difficulty understanding how to import the newly built file. I added `/*eslint-disable` at the beginning of the build file at the linting errors doesn't show anymore. Now when I import it, it says there are no default exports.

**Comment by ma2ciek** [comment]
Hi @Robyrogers,

Could you provide the exact error message?

You should build the editor using the https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html guide if you want to customize it, so the default export should be available in this file after the build.

**Comment by Robyrogers** [comment]
Hi @ma2ciek 
These are the errors. I can't seem to use the build file.
![Screenshot from 2019-08-03 16-27-31](https://user-images.githubusercontent.com/11811491/62410705-c525e000-b60b-11e9-9934-1ec727340625.png)
![Screenshot from 2019-08-03 16-27-39](https://user-images.githubusercontent.com/11811491/62410710-cbb45780-b60b-11e9-93c6-22800d5994ab.png)

**Comment by Mgsy** [comment]
I've checked your issue and indeed I can reproduce the error after importing the local build. 
Steps to reproduce:
1. Create a new project with `create-react-app`.
1. Clone `ckeditor5-build-classic` repository to the `src` directory.
1. Import the editor from the cloned repo.

@pomek, can you try to investigate it?

**Comment by pomek** [comment]
Sorry guys but I am not able to reproduce the issue due to my PC limitation. Increasing the node's limit doesn't help.

```
<--- Last few GCs --->

[10762:0x103b19000]    63851 ms: Scavenge 1373.7 (1422.7) -> 1373.0 (1423.7) MB, 10.4 / 0.0 ms  (average mu = 0.122, current mu = 0.077) allocation failure
[10762:0x103b19000]    63861 ms: Scavenge 1373.9 (1423.7) -> 1373.0 (1424.2) MB, 5.9 / 0.0 ms  (average mu = 0.122, current mu = 0.077) allocation failure
[10762:0x103b19000]    63871 ms: Scavenge 1373.9 (1424.2) -> 1373.1 (1424.7) MB, 7.7 / 0.0 ms  (average mu = 0.122, current mu = 0.077) allocation failure


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x1942a53dbe3d]
Security context: 0x01509551e6e9 <JSObject>
    1: SourceMapConsumer_allGeneratedPositionsFor [0x15037b3f881] [/Users/pomek/Projects/pomek/react-app/node_modules/@babel/core/node_modules/source-map/lib/source-map-consumer.js:~178] [pc=0x1942a5c4f1e2](this=0x01505ef82291 <BasicSourceMapConsumer map = 0x1504bbd2cc9>,aArgs=0x0150cb952379 <Object map = 0x1504bbd16c9>)
    2: /* anonymous */(aka /* anonymo...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

But, AFAICS and what I can say:

- Those imports below are equal to each other from the Node point of view

    ```js
    import Editor from './ckeditor5-build-classic/build/ckeditor';
    // vs.
    import Editor from '@ckeditor/ckeditor5-build-classic';
    ```

    Because `@ckeditor/ckeditor5-build-classic` has defined the main file https://github.com/ckeditor/ckeditor5-build-classic/blob/66a0e5c8136974a97d3513f3770aead243a175c4/package.json#L23
- React scripts ignore parsing stuff from the `node_modules/` directory where all packages are installed.
- React scripts parse all stuff found in the `src/` directory which (by default) is the directory where a user has written his app.
- There is no problem if you import the package in such way:

  ```js
  import Editor from '@ckeditor/ckeditor5-build-classic'
  ``` 

  The import above is equal to the import below:

  ```
  import Editor from '@ckeditor/ckeditor5-build-classic/build/ckeditor'
  ```

 Which means that some pre-processor from React script touches the file when it is saved in the `src/` directory.

- If you would like to create a custom build, I really recommend following the guide – https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html.
- But, if you want to clone the entire repository, would be good to modify webpack's config to ignore the entire code inside the cloned package.

**Comment by Robyrogers** [comment]
@pomek Thank you for your suggested solution. I will try it out and hopefully will be able customize the editor the way I want to.
